function SetPsweepParams(pnax, psweepparams)
%Set power sweep parameters
    fprintf(pnax.instrhandle, 'SENSe%d:SWEep:TYPE POWer', ...
            psweepparams.channel);
    fprintf(pnax.instrhandle, 'SENse%d:FOM OFF', ...
            psweepparams.channel);
    fprintf(pnax.instrhandle, 'SENse%d:FOM:DISPlay:SELect ''receivers''', ...
            psweepparams.channel);
    fprintf(pnax.instrhandle, 'SOURce%d:POWer1:ATTenuation:AUTO ON', ...
            psweepparams.channel);
	fprintf(pnax.instrhandle, 'SOURce%d:POWer1:STARt %g', ...
            [psweepparams.channel, psweepparams.start]);
	fprintf(pnax.instrhandle, 'SOURce%d:POWer1:STOP %g', ...
            [psweepparams.channel, psweepparams.stop]);
    fprintf(pnax.instrhandle, 'SENSe%d:SWEep:POINts %g', ...
            [psweepparams.channel, psweepparams.points]);
    fprintf(pnax.instrhandle, 'SOURce%d:POWer3:MODE AUTO', ...
            psweepparams.channel);
    fprintf(pnax.instrhandle, 'SENSe%d:FREQuency:CW %g', ...
            [psweepparams.channel, psweepparams.cwfreq]);
    fprintf(pnax.instrhandle, 'SENSe%d:BANDwidth %g', ...
            [psweepparams.channel, psweepparams.ifbandwidth]);
    fprintf(pnax.instrhandle, 'SENSe%d:AVERage:COUNt %d', ...
            [psweepparams.channel, psweepparams.averages]);
    fprintf(pnax.instrhandle, 'CALCulate%d:FORMat %s', ...
            [psweepparams.channel, psweepparams.format]);    
end