function SetTransParams(pnax, transparams)
% Set transmission parameters
    fprintf(pnax.instrhandle, 'SENSe%d:SWEep:TYPE LINear', ...
            transparams.channel);
    fprintf(pnax.instrhandle, 'SENse%d:FOM OFF', ...
            transparams.channel);
    fprintf(pnax.instrhandle, 'SENse%d:FOM:DISPlay:SELect ''receivers''', ...
            transparams.channel);
    fprintf(pnax.instrhandle, 'SENSe%d:FREQuency:STARt %f', ...
            [transparams.channel, transparams.start]);
    fprintf(pnax.instrhandle, 'SENSe%d:FREQuency:STOP %f', ...
            [transparams.channel, transparams.stop]);
    fprintf(pnax.instrhandle, 'SENSe%d:SWEep:POINts %d', ...
            [transparams.channel, transparams.points]);
    fprintf(pnax.instrhandle, sprintf('SOURce%d:POWer%s %f', ...
                                      transparams.channel, ...
                                      transparams.meastype(end), ...
                                      transparams.power));
    fprintf(pnax.instrhandle, 'SOURce%d:POWer3:MODE AUTO', ...
            transparams.channel);
    fprintf(pnax.instrhandle, 'SENSe%d:BANDwidth %f', ...
            [transparams.channel, transparams.ifbandwidth]);
    fprintf(pnax.instrhandle, 'SENSe%d:AVERage:COUNt %d', ...
            [transparams.channel, transparams.averages]);
    fprintf(pnax.instrhandle, 'SENSe%d:AVERage:MODE %s', ...
            [transparams.channel, transparams.avgmode]);
    fprintf(pnax.instrhandle, 'CALCulate%d:FORMat %s', ...
            [transparams.channel, transparams.format]);
end