function SetTransParams(pnax, transparams)
% Set transmission measurement
    fprintf(pnax.instrhandle, 'SENSe%d:SWEep:TYPE LINear', ...
            transparams.channel);
    fprintf(pnax.instrhandle, 'SENse%d:FOM OFF', ...
            transparams.channel);
    fprintf(pnax.instrhandle, 'SENse%d:FOM:DISPlay:SELect ''receivers''', ...
            transparams.channel);
    fprintf(pnax.instrhandle, 'SENSe%d:FREQuency:STARt %g', ...
            [transparams.channel, transparams.start]);
    fprintf(pnax.instrhandle, 'SENSe%d:FREQuency:STOP %g', ...
            [transparams.channel, transparams.stop]);
    fprintf(pnax.instrhandle, 'SENSe%d:SWEep:POINts %g', ...
            [transparams.channel, transparams.points]);
    fprintf(pnax.instrhandle, 'SOURce%d:POWer1 %g', ...
            [transparams.channel, transparams.power]);
    fprintf(pnax.instrhandle, 'SOURce%d:POWer3:MODE AUTO', ...
            transparams.channel);
    fprintf(pnax.instrhandle, 'SENSe%d:BANDwidth %g', ...
            [transparams.channel, transparams.ifbandwidth]);
    fprintf(pnax.instrhandle, 'SENSe%d:AVERage:COUNt %d', ...
            [transparams.channel, transparams.averages]);
    fprintf(pnax.instrhandle, 'CALCulate%d:FORMat %s', ...
            [transparams.channel, transparams.format]);
end