delay = 0;
fixedPt = 1200;
cycleLen = 1500;
pg = PatternGen;
echotimes = 0:10:1000;
patseq = {pg.pulse('X90p'),...
			pg.pulse('QId', 'width', echotimes),...
			pg.pulse('Yp'), ...
			pg.pulse('QId', 'width', echotimes),...
			pg.pulse('X90p')};
[patx paty] = pg.getPatternSeq(patseq, 1, delay, fixedPt);
plot(patx);hold on;plot(paty,'r');