% Returns a waveform and associated descriptors, in one of several possible formats
% This function is the preferred way of reading waveforms, since it includes the capabilities
% of all the other read functions, and more!
%
% Please refer to the Programmer's Reference Manual for more information.
%

% (c) Copyright 2005, 2006-2009 Agilent Technologies, Inc.
% $Id: AqD1_readData.m 33903 2009-01-26 16:45:39Z bdonnier $

function [status dataDesc segDescArray dataArray] = AqD1_readData(instrumentID, channel, readParAnyOrder)
% The MEX parameters are transferred by a memory copy. In the case of a
% structure, we must be sure that we send the elements in the same order as they are read.
try
    readPar = struct(   'dataType', readParAnyOrder.dataType, ...
                        'readMode', readParAnyOrder.readMode, ...
                        'firstSegment', readParAnyOrder.firstSegment, ...
                        'nbrSegments', readParAnyOrder.nbrSegments, ...
                        'firstSampleInSeg', readParAnyOrder.firstSampleInSeg, ...
                        'nbrSamplesInSeg', readParAnyOrder.nbrSamplesInSeg, ...
                        'segmentOffset', readParAnyOrder.segmentOffset, ...
                        'dataArraySize', readParAnyOrder.dataArraySize, ...
                        'segDescArraySize', readParAnyOrder.segDescArraySize, ...
                        'flags', readParAnyOrder.flags, ...
                        'reserved', readParAnyOrder.reserved, ...
                        'reserved2', readParAnyOrder.reserved2, ...
                        'reserved3', readParAnyOrder.reserved3);
catch
    error('Read parameters structure invalid.')
end
                    
[status dataDesc segDescArray dataArray] = AqDrvMex('AqD1_readData', instrumentID, channel, readPar);
