function freq = GetFreq(self)
    % Get frequency
    self.CheckInstr();
    rfvalues = struct('rf1_freq', 0, ...
                  'start_freq', 0, ...
                  'stop_freq', 0, ...
                  'step_freq', 0, ...
                  'sweep_dwell_time', 0, ...
                  'sweep_cycles', 0, ...
                  'buffer_points', 0, ...
                  'rf_level', 0, ...
                  'rf2_freq', 0);
    rfparams = libstruct('device_rf_params_t', rfvalues);
    status = calllib(self.lib, 'sc5511a_get_rf_parameters', self.instr, rfparams);
    freq = rfparams.rf1_freq;
end