function status = GetStatus(self)
    
    list_mode_values = struct('sss_mode', 0, ...
                  'sweep_dir', 0, ...
                  'tri_waveform', 0, ...
                  'hw_trigger', 0, ...
                  'step_on_hw_trig', 0, ...
                  'return_to_start', 0, ...
                  'trig_out_enable', 0, ...
                  'trig_out_on_cycle', 0);
    list_mode_pointer = libstruct('list_mode_t', list_mode_values);
    
    pll_status_values = struct('sum_pll_ld', 0, ...
                  'crs_pll_ld', 0, ...
                  'fine_pll_ld', 0, ...
                  'crs_ref_pll_ld', 0, ...
                  'crs_aux_pll_ld', 0, ...
                  'ref_100_pll_ld', 0, ...
                  'ref_10_pll_ld', 0, ...
                  'rf2_pll_ld', 0);
    pll_status_pointer = libstruct('pll_status_t', pll_status_values);
    
    operate_status_values = struct('rf1_lock_mode', 0, ...
                  'rf1_loop_gain', 0, ...
                  'device_access', 0, ...
                  'rf2_standby', 0, ...
                  'rf1_standby', 0, ...
                  'auto_pwr_disable', 0, ...
                  'alc_mode', 0, ...
                  'rf1_out_enable', 0, ...
                  'ext_ref_lock_enable', 0, ...
                  'ext_ref_detect', 0, ...
                  'ref_out_select', 0, ...
                  'list_mode_running', 0, ...
                  'rf1_mode', 0, ...
                  'over_temp', 0, ...
                  'harmonic_ss', 0);
    operate_status_pointer = libstruct('operate_status_t', operate_status_values);

    device_status_values = struct('list_mode', list_mode_pointer, ...
                                  'pll_status', pll_status_pointer, ...
                                  'operate_status', operate_status_pointer);
    device_status_pointer = libstruct('device_status_t', device_status_values);
    
    calllib(self.lib, 'sc5511a_get_device_status', self.instr, device_status_pointer);
    
    status = get(device_status_pointer);
end