function info = Info(self)
% Get device info
    self.CheckInstr();
    
    date = struct('year', 0, ...
                  'month', 0, ...
                  'day', 0, ...
                  'hour', 0);
    date_pointer = libstruct('date_t', date);
    info = struct('product_serial_number', 0, ...
                  'hardware_revision', 0, ...
                  'firmware_revision', 0, ...
                  'man_date', date_pointer);
    info_pointer = libstruct('device_info_t', info);
    calllib(self.lib, 'sc5511a_get_device_info', self.instr, info_pointer);
    info = get(info_pointer);
end